export type AgentErrorCode =
  | 'RELATIONSHIP_NOT_FOUND'
  | 'RELATIONSHIP_NOT_AVAILABLE'
  | 'RECIPIENT_MISMATCH'
  | 'POLICY_NOT_FOUND'
  | 'POLICY_RELATIONSHIP_MISMATCH'
  | 'SESSION_NOT_FOUND'
  | 'SESSION_RELATIONSHIP_MISMATCH'
  | 'RECIPIENT_ENTRY_REQUIRED'
  | 'PROACTIVE_TRIGGER_NOT_ALLOWED'
  | 'INSUFFICIENT_CONTEXT'
  | 'INTERACTION_NOT_FOUND'
  | 'INVALID_INTERACTION_TRANSITION'
  | 'RELATIONSHIP_VERSION_UNSUPPORTED'
  | 'INTERACTION_SCOPE_MISMATCH'
  | 'GENERATION_POLICY_NOT_FOUND'
  | 'POLICY_SCOPE_MISMATCH'
  | 'TRIGGER_NOT_ALLOWED'
  | 'SOURCE_REQUIRED'
  | 'SOURCE_NOT_FOUND'
  | 'SOURCE_NOT_ALLOWED'
  | 'PRIVATE_SOURCE'
  | 'CROSS_RELATIONSHIP_SOURCE'
  | 'FORBIDDEN_TOPIC'
  | 'TOPIC_NOT_ALLOWED'
  | 'MODE_NOT_ALLOWED'
  | 'HIGH_RISK_BLOCKED'
  | 'ORIGINAL_ASSET_NOT_FOUND'
  | 'OWNER_REVIEW_REQUIRED'
  | 'UNSAFE_GENERATION'
  | 'INVALID_GENERATION_RESULT'

export class AgentError extends Error {
  constructor(
    readonly code: AgentErrorCode,
    message: string,
  ) {
    super(message)
    this.name = 'AgentError'
  }
}
